### ISSUE TITLE
example solutions are missing for example issues!

### ISSUE THREAD

**Issue by fpusan** [coderefinery/template-centralized-workflow-exercise#6]
see title

**Comment by bast** [comment]
Sorry I am not sure I understand the issue. I am closing but please reopen if this is still an issue.

**Comment by fpusan** [comment]
I posted this as part of an exercise for last year's github workshop... possibly this was the wrong place and should have been done in a cloned instead.

**Comment by bast** [comment]
Ah good. I did not notice until today. Thanks for clarification.
